// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5cDa3jnDgBMCxftv1HWtQAOi2vk9wN-I',
    appId: '1:365530487926:web:59e1373241b226229cd357',
    messagingSenderId: '365530487926',
    projectId: 'auth-testing-e7616',
    authDomain: 'auth-testing-e7616.firebaseapp.com',
    storageBucket: 'auth-testing-e7616.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxk4n39-1970K85v7LUFJy-dxpzNCeuL8',
    appId: '1:365530487926:android:70e799db7f3e2af09cd357',
    messagingSenderId: '365530487926',
    projectId: 'auth-testing-e7616',
    storageBucket: 'auth-testing-e7616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkusy3X3xKfkX-ve_MgHTCUL1fMVWb3A',
    appId: '1:365530487926:ios:b1f3b3ddb7eb04b39cd357',
    messagingSenderId: '365530487926',
    projectId: 'auth-testing-e7616',
    storageBucket: 'auth-testing-e7616.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQkusy3X3xKfkX-ve_MgHTCUL1fMVWb3A',
    appId: '1:365530487926:ios:b1f3b3ddb7eb04b39cd357',
    messagingSenderId: '365530487926',
    projectId: 'auth-testing-e7616',
    storageBucket: 'auth-testing-e7616.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5cDa3jnDgBMCxftv1HWtQAOi2vk9wN-I',
    appId: '1:365530487926:web:691c97e0750b9e6e9cd357',
    messagingSenderId: '365530487926',
    projectId: 'auth-testing-e7616',
    authDomain: 'auth-testing-e7616.firebaseapp.com',
    storageBucket: 'auth-testing-e7616.firebasestorage.app',
  );
}
